version: "3"
services:
  blockchain:
    image: trubudget/blockchain:latest
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      MULTICHAIN_FEED: ${MULTICHAIN_FEED}
      LOG_LEVEL: ${LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
    # volume for persisting data from multichain
    volumes:
      - ~/masterVolume:/root/.multichain
    ports:
      - "8000:8000"
      - "8085:8085"

  api:
    image: trubudget/api:latest
    environment:
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      RPC_HOST: blockchain
      RPC_PORT: ${RPC_PORT}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION_PUBLIC_KEY: ${ORGANIZATION_PUBLIC_KEY}
      ORGANIZATION_PRIVATE_KEY: ${ORGANIZATION_PRIVATE_KEY}
      ENCRYPTION_PASSWORD: ${ENCRYPTION_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SIGNING_METHOD: ${SIGNING_METHOD}
      NODE_ENV: ${NODE_ENV}
      ACCESS_CONTROL_ALLOW_ORIGIN: ${ACCESS_CONTROL_ALLOW_ORIGIN}
      LOG_LEVEL: ${API_LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
    depends_on:
      - blockchain
    ports:
      - ${API_PORT}:${API_PORT}

  provisioning:
    image: trubudget/provisioning:latest
    command: [ "npm", "start" ]
    environment:
      API_HOST: api
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: TEST
      #Other provisioning data:
      #ENVIRONMENT_TYPE: PROD
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
      LOG_LEVEL: ${PROVISIONING_LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
    depends_on:
      - api
